services:
  - type: worker
    name: art-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python art_bot.py"
    autoDeploy: true
